### PR TITLE
Refactor the run commands to be kinpin sub-commands

### PR DESCRIPTION
**Pull request by hellais**
This makes it easier to have command specific options such as --url for
the websites test

### CODE REVIEW

**Comment by hellais** [comment]
@bassosimone do you have any hints as to why the linux build is failing?

I see some linking errors:

```
# github.com/ooni/probe-cli/cmd/ooni
/usr/lib/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-906224136/000000.o: unable to initialize decompress status for section .debug_info
/tmp/go-link-906224136/000000.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by bassosimone** [comment]
Do you mind to continue this after #46 has been merged?

**Comment by hellais** [comment]
Yeah I can do that

**Comment by bassosimone** [comment]
🙏

**Comment by hellais** [comment]
This is now blocking on getting https://github.com/ooni/probe-engine/pull/39 as it would be preferable to configure the CI to only run a subset of the full lists.

**Comment by bassosimone** [comment]
I've determined that this PR is fully contained by #53 after solving the merge conflicts in a reasonable way, so I am going to close it.

**Pull request closed without merging**
