### PR TITLE
Bump to 3.0.0-rc.1

### PR DESCRIPTION
**Pull request by hellais**
Needed for: https://github.com/ooni/probe-desktop/pull/74

### CODE REVIEW

**Comment by sarathms** [comment]
The filenames of the tarbals do not match the ones in `checksums.txt`.

**Comment by hellais** [comment]
> The filenames of the tarbals do not match the ones in checksums.txt.

Really?

I see in `ooniprobe-checksums.txt`:
```
6a9e6f0db5e742200e780a5e415392cb20455aef5f4ed8ab46c72259004c41ae  ooniprobe_v3.0.0-rc.1_linux_amd64.tar.gz
287f4f5c8f735e58bf81fdce2fdecf62c7e81f0116379882d52fad495f9692e8  ooniprobe_v3.0.0-rc.1_darwin_amd64.tar.gz
e07f99a030b45d6961501f6b5680ec535260aa4bcc61d9e57640f7ea5b2a6e0f  ooniprobe_v3.0.0-rc.1_windows_amd64.tar.gz
```

and in the uploaded assets are:
```
ooniprobe_v3.0.0-rc.1_darwin_amd64.tar.gz
17.6 MB
ooniprobe_v3.0.0-rc.1_linux_amd64.tar.gz
22.4 MB
ooniprobe_v3.0.0-rc.1_windows_amd64.tar.gz
19.6 MB
```

**Comment by hellais** [comment]
Note: I haven't actually done extensive testing of this release candidate and I suggest we use a new RC for the probe-desktop release candidate that also includes: https://github.com/ooni/probe-engine/pull/104

**Comment by sarathms** [comment]
The filenames were missing the `v` before the version number. The checksum file itself was named`checksums.txt`. I renamed all of them. Uploaded again and signed the checksum file.

**Comment by bassosimone** [comment]
I'm going to merge this PR and cut a new `-rc` with ooni/probe-engine@v0.2.0.

**Pull request merged**
