### PR TITLE
feat: relicense the repository under GNU GPLv3

### PR DESCRIPTION
**Pull request by bassosimone**
## Checklist

- [x] I have read the [contribution guidelines](https://github.com/ooni/probe-cli/blob/master/CONTRIBUTING.md)
- [x] reference issue for this pull request: N/A (this is planned maintenance)
- [x] related ooni/spec pull request: N/A

Location of the issue tracker: https://github.com/ooni/probe

## Description

We're going to integrate some pieces of code under the GNU GPLv3
soon, therefore we also need to relicense this repository.

### CODE REVIEW

**Comment by bassosimone** [comment]
I have created https://github.com/ooni/probe/issues/1750 for the failure at https://github.com/ooni/probe-cli/pull/446/checks?check_run_id=3381985435. We can merge anyway because this change does not affect the code.

**Comment by chenrui333** [comment]
@bassosimone 👋  `GPL-3.0` is actually a [deprecated SPDX license](https://spdx.org/licenses/GPL-3.0.html), can you specify in either README or any file header about which latest license (`GPL-3.0-or-later` or `GPL-3.0-only`) would be actually applied. Let me know if that makes sense. Thanks!

**Comment by bassosimone** [comment]
Absolutely! Is this fine/enough https://github.com/ooni/probe-cli/pull/641 ?

**Comment by chenrui333** [comment]
Yes, thanks for confirming it so quickly!

**Comment by bassosimone** [comment]
My pleasure! Thank you folks for Homebrew, it's a really nice tool!

**Pull request merged**
